/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionintervencion;

import clinicadental.*;
import gestionagenda.JFrameAgenda;
import gestionarticulos.JFrameArticulos;
import gestionpacientes.JFramePacientes;
import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author Lucky
 */
public class JFrameIntervencion extends javax.swing.JFrame {

    /**
     * Creates new form LoginJframe
     */
    public JFrameIntervencion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelContenido = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jButtonArticulo = new javax.swing.JButton();
        jButtonSalir1 = new javax.swing.JButton();
        jButtonEmpleado = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jButtonIntervencion = new javax.swing.JButton();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIntervenciones = new javax.swing.JTable();
        jButtonModInterv = new javax.swing.JButton();
        jButtonBajaInterv = new javax.swing.JButton();
        jButtonEliminarInterv = new javax.swing.JButton();
        jButtonBuscarInterv = new javax.swing.JButton();
        jButtonFiltrarInterv = new javax.swing.JButton();
        jButtonAnadirInterv = new javax.swing.JButton();
        jLabelImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelContenido.setOpaque(false);
        jPanelContenido.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Gestión de Intervenciónes");

        jLabelError.setForeground(new java.awt.Color(204, 0, 0));

        jButtonArticulo.setBackground(new java.awt.Color(153, 204, 255));
        jButtonArticulo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonArticulo.setText("ARTÍCULOS");
        jButtonArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArticuloActionPerformed(evt);
            }
        });

        jButtonSalir1.setBackground(new java.awt.Color(153, 204, 255));
        jButtonSalir1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonSalir1.setText("SALIR");

        jButtonEmpleado.setBackground(new java.awt.Color(153, 204, 255));
        jButtonEmpleado.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonEmpleado.setText("EMPLEADOS");

        jButtonPaciente.setBackground(new java.awt.Color(153, 204, 255));
        jButtonPaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonPaciente.setText("PACIENTES");
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });

        jButtonAgenda.setBackground(new java.awt.Color(153, 204, 255));
        jButtonAgenda.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonAgenda.setText("AGENDA");
        jButtonAgenda.setFocusable(false);
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });

        jButtonIntervencion.setBackground(new java.awt.Color(255, 204, 102));
        jButtonIntervencion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonIntervencion.setText("INTERVENCIONES");

        jPanelTabla.setOpaque(false);

        jTableIntervenciones.setAutoCreateRowSorter(true);
        jTableIntervenciones.setModel(new javax.swing.table.DefaultTableModel(datos(),cabecera()){
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableIntervenciones);

        jButtonModInterv.setBackground(new java.awt.Color(0, 128, 192));
        jButtonModInterv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModInterv.setText("Modificar");

        jButtonBajaInterv.setBackground(new java.awt.Color(0, 128, 192));
        jButtonBajaInterv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBajaInterv.setText("Baja");

        jButtonEliminarInterv.setBackground(new java.awt.Color(0, 128, 192));
        jButtonEliminarInterv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarInterv.setText("Eliminar");

        jButtonBuscarInterv.setBackground(new java.awt.Color(0, 128, 192));
        jButtonBuscarInterv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarInterv.setText("Buscar");
        jButtonBuscarInterv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarIntervActionPerformed(evt);
            }
        });

        jButtonFiltrarInterv.setBackground(new java.awt.Color(0, 128, 192));
        jButtonFiltrarInterv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFiltrarInterv.setText("Filtrar");

        jButtonAnadirInterv.setBackground(new java.awt.Color(0, 128, 192));
        jButtonAnadirInterv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnadirInterv.setText("Añadir");
        jButtonAnadirInterv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirIntervActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablaLayout.createSequentialGroup()
                        .addComponent(jButtonAnadirInterv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModInterv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBajaInterv)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarInterv))
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addComponent(jButtonBuscarInterv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFiltrarInterv)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarInterv)
                    .addComponent(jButtonFiltrarInterv))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModInterv)
                    .addComponent(jButtonBajaInterv)
                    .addComponent(jButtonEliminarInterv)
                    .addComponent(jButtonAnadirInterv))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonIntervencion)
                                    .addComponent(jButtonAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );

        jPanelContenidoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAgenda, jButtonArticulo, jButtonEmpleado, jButtonIntervencion, jButtonPaciente, jButtonSalir1});

        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitulo)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButtonAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIntervencion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jButtonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanelContenido, gridBagConstraints);

        jLabelImgFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabelImgFondo.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabelImgFondo.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabelImgFondo.setPreferredSize(new java.awt.Dimension(800, 600));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabelImgFondo, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Rellena la tabla de intervenciones
     * 
     * @param Evento de ventana abierta
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        rellenarTabla();
    }//GEN-LAST:event_formWindowOpened

    /**
     * Abre la ventana de Agenda y cierra la actual
     * 
     * @param Evento de Boton Agenda
     */
    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        JFrameAgenda agenda = new JFrameAgenda();
        agenda.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    /**
     * Abre la ventana de Pacientes y cierra la actual
     * 
     * @param Evento de Boton Paciente
     */
    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        JFramePacientes pacientes = new JFramePacientes();
        pacientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    /**
     * Abre la ventana de Articulo y cierra la actual
     * 
     * @param Evento de Boton Articulo
     */
    private void jButtonArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArticuloActionPerformed
        JFrameArticulos articulos = new JFrameArticulos();
        articulos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonArticuloActionPerformed

    private void jButtonBuscarIntervActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarIntervActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarIntervActionPerformed

    private void jButtonAnadirIntervActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirIntervActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnadirIntervActionPerformed
    
    /**    
     * Rellena la tabla con las intervenciones guardadas en Clinica
     */
    private void rellenarTabla() {
        ArrayList<Intervencion> intervenciones = Clinica.getIntervenciones();
        
        for (int i = 0; i < intervenciones.size(); i++) {
            for (int j = 0; j < intervenciones.get(i).datosTabla().length; j++) {
                jTableIntervenciones.setValueAt(intervenciones.get(i).datosTabla()[j],i,j);
            }
        }
    }
    
    /**
     * Recopila la cantidad de datos que contiene los intervenciones en clinica,
     * necesaria para crear el model de la tabla
     * 
     * @return Object[][] que contiene unicamente la cantidad de datos
     */    
    private Object[][] datos() {
        ArrayList<Intervencion> intervenciones = Clinica.getIntervenciones();
        Object[][] datos = new Object[intervenciones.size()][cabecera().length];
        
        for (int i = 0; i < intervenciones.size(); i++)
        {
            for (int j = 0; j < cabecera().length; j++){
                datos[i][j] = null;                
            }
        }
        return datos;
    }
    
    /**
     * Guarda las cabeceras de la Tabla
     * 
     * @return String[] con los nombres de las cabeceras de la tabla
     */
    private String[] cabecera() {
        String[] cabecera = {"Nombre", "Duración", "Precio", "Especialista"};
        return cabecera;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIntervencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIntervencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIntervencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIntervencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFramePacientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonAnadirInterv;
    private javax.swing.JButton jButtonArticulo;
    private javax.swing.JButton jButtonBajaInterv;
    private javax.swing.JButton jButtonBuscarInterv;
    private javax.swing.JButton jButtonEliminarInterv;
    private javax.swing.JButton jButtonEmpleado;
    private javax.swing.JButton jButtonFiltrarInterv;
    private javax.swing.JButton jButtonIntervencion;
    private javax.swing.JButton jButtonModInterv;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonSalir1;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelImgFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableIntervenciones;
    // End of variables declaration//GEN-END:variables
}
