/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionagenda;

import clinicadental.*;
import gestionpacientes.Paciente;
import gestionintervencion.Intervencion;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Lucky
 */
public class JFrameNuevaCita extends javax.swing.JFrame {

    /**
     * Creates new form LoginJframe
     */
    public JFrameNuevaCita(Paciente p) {
        initComponents();
        this.paciente = p;
        seleccionIntervencion();
        mostrarPaciente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelContenido = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jPanelAltaPacienteForm = new javax.swing.JPanel();
        jCalendarFechaCita = new com.toedter.calendar.JCalendar();
        jLabelIntervencion = new javax.swing.JLabel();
        jComboBoxIntervenciones = new javax.swing.JComboBox();
        jLabelDuracion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelDatosCita = new javax.swing.JLabel();
        jButtonCancelarNuevaCita = new javax.swing.JButton();
        jButtonGuardarCita = new javax.swing.JButton();
        jLabelPaciente = new javax.swing.JLabel();
        jLabelImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelContenido.setOpaque(false);
        jPanelContenido.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Añadir Cita");

        jLabelError.setForeground(new java.awt.Color(204, 0, 0));

        jPanelAltaPacienteForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 135, 135)));
        jPanelAltaPacienteForm.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanelAltaPacienteForm.setOpaque(false);

        jLabelIntervencion.setText("Intervención:");

        String[] nombreIntervenciones = new String[Clinica.getIntervenciones().size()];
        ArrayList<Intervencion> intervenciones = Clinica.getIntervenciones();

        for (int i = 0; i < intervenciones.size(); i++){
            nombreIntervenciones[i] = intervenciones.get(i).getNombre();
        }
        jComboBoxIntervenciones.setModel(new javax.swing.DefaultComboBoxModel(nombreIntervenciones));
        jComboBoxIntervenciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIntervencionesActionPerformed(evt);
            }
        });

        jLabelDuracion.setText("Duración:");

        jLabel1.setText("Hora");

        jLabel2.setText(":");

        javax.swing.GroupLayout jPanelAltaPacienteFormLayout = new javax.swing.GroupLayout(jPanelAltaPacienteForm);
        jPanelAltaPacienteForm.setLayout(jPanelAltaPacienteFormLayout);
        jPanelAltaPacienteFormLayout.setHorizontalGroup(
            jPanelAltaPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltaPacienteFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAltaPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAltaPacienteFormLayout.createSequentialGroup()
                        .addGroup(jPanelAltaPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCalendarFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAltaPacienteFormLayout.createSequentialGroup()
                                .addComponent(jLabelIntervencion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxIntervenciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabelDuracion))
                    .addGroup(jPanelAltaPacienteFormLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAltaPacienteFormLayout.setVerticalGroup(
            jPanelAltaPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltaPacienteFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAltaPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIntervencion)
                    .addComponent(jComboBoxIntervenciones, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDuracion))
                .addGap(27, 27, 27)
                .addComponent(jCalendarFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAltaPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabelDatosCita.setForeground(new java.awt.Color(135, 135, 135));
        jLabelDatosCita.setText("Datos de la cita:");

        jButtonCancelarNuevaCita.setBackground(new java.awt.Color(0, 128, 192));
        jButtonCancelarNuevaCita.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarNuevaCita.setText("Cancelar");
        jButtonCancelarNuevaCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarNuevaCitaActionPerformed(evt);
            }
        });

        jButtonGuardarCita.setBackground(new java.awt.Color(0, 128, 192));
        jButtonGuardarCita.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardarCita.setText("Guardar");
        jButtonGuardarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCitaActionPerformed(evt);
            }
        });

        jLabelPaciente.setForeground(new java.awt.Color(135, 135, 135));
        jLabelPaciente.setText("Paciente:");

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addComponent(jButtonGuardarCita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelarNuevaCita))
                    .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                            .addComponent(jLabelDatosCita)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPaciente))
                        .addComponent(jPanelAltaPacienteForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitulo)
                .addGap(90, 90, 90)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatosCita)
                    .addComponent(jLabelPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAltaPacienteForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarNuevaCita)
                    .addComponent(jButtonGuardarCita))
                .addGap(18, 18, 18)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanelContenido, gridBagConstraints);

        jLabelImgFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabelImgFondo.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabelImgFondo.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabelImgFondo.setPreferredSize(new java.awt.Dimension(800, 600));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabelImgFondo, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jButtonGuardarCita.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonCancelarNuevaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarNuevaCitaActionPerformed
        /*JFramePacientes pacientes = new JFramePacientes();
        pacientes.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButtonCancelarNuevaCitaActionPerformed

    private void jButtonGuardarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCitaActionPerformed
       /* anadirPaciente();
        JFramePacientes pacientes = new JFramePacientes();
        pacientes.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButtonGuardarCitaActionPerformed

    private void jComboBoxIntervencionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIntervencionesActionPerformed
        seleccionIntervencion();
    }//GEN-LAST:event_jComboBoxIntervencionesActionPerformed
    
    private void seleccionIntervencion(){
        String opc = String.valueOf(jComboBoxIntervenciones.getSelectedItem());
        
        for (Intervencion i : Clinica.getIntervenciones()) {
            if(opc.equals(i.getNombre())){
                mostrarDuracion(i.getDuracion());
                intervencionSeleccionada = i;
            }
        }
    }
    
    private void mostrarDuracion(int duracion){        
        jLabelDuracion.setText("Duracion: "+duracion+" minutos");          
    }
    
    private void activaGuardar(){
        /*if(!jTextFieldDni.getText().equals("") && !jTextFieldTelefono.getText().equals("")
            && !jTextFieldNombre.getText().equals("") && !jTextFieldApe1.getText().equals("")
            && !jTextFieldApe2.getText().equals("") && !jTextFieldHora.getText().equals("")
            && jDateChooserFechaNac.getDate() != null) 
            if(esNumero(jTextFieldTelefono.getText()) && esNumero(jTextFieldTelefono.getText()))
                jButtonGuardarCita.setEnabled(true);*/
    }
    
    private boolean esNumero(String s){
        try{
            int num = Integer.parseInt(s);
            return true;
        }catch(NumberFormatException e){
            return false;        
        }
    }
    
    private void anadirPaciente(){
       /* int dni = 0;
        int tlf = 0;
        Date fechaNac = jDateChooserFechaNac.getDate();
        
        try{
            dni = Integer.parseInt(jTextFieldDni.getText());
        }catch(NumberFormatException e){
            jLabelError.setText("\"DNI\" es un campo NUMERICO");
        }
        
        try{            
            tlf = Integer.parseInt(jTextFieldTelefono.getText());
        }catch(NumberFormatException e){
            jLabelError.setText("\"Telefono\" es un campo NUMERICO");
        } 
        
        Paciente[] p = {new Paciente(dni,
                                    jTextFieldNombre.getText(),
                                    jTextFieldApe1.getText(),
                                    jTextFieldApe2.getText(),
                                    tlf,
                                    fechaNac)};
        
        Clinica.anadirPaciente(p);*/
    }
    
    private void mostrarPaciente(){
        jLabelPaciente.setText("Paciente: "+paciente.getNombre()+", "+paciente.getApellido1());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFrameNuevaCita(null).setVisible(true);
            }
        });
    }
    
    private Paciente paciente;
    private Intervencion intervencionSeleccionada;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarNuevaCita;
    private javax.swing.JButton jButtonGuardarCita;
    private com.toedter.calendar.JCalendar jCalendarFechaCita;
    private javax.swing.JComboBox jComboBoxIntervenciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDatosCita;
    private javax.swing.JLabel jLabelDuracion;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelImgFondo;
    private javax.swing.JLabel jLabelIntervencion;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelAltaPacienteForm;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
